//
//  project-euler-problem-2.c
//
// Project Euler Problem 2
//
/*  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
//
//  Created by Jerrod Smith on 2017-04-26.
//
//

#include <stdio.h>

int main()
{
    int A; // the odd-index terms in the Fibonacci sequence
    int B; // the even-index terms in the Fibonacci sequence
    int i; // the i^th term in the Fibonacci sequence; we'll sum over this variable
    int sum; // the sum of the even Fibonacci numbers less than four million
    // Tell the user what we're doing
    printf("We're going to find the sum of the even Fibonacci numbers (starting with 1,2) whose values are less than four million.\n");
    
    // set A=1 and B=2 to start the sequence
    A=1;
    B=2;
    
    // set sum = 0 to start
    sum = 0;
    
    // set up a loop to compute the sum
    do{
        i = A; // start at the first, third, fifth terms
        
        // determine if we add i to the sum; prevent i from exceeding 4 000 000
        if(i % 2 ==0 && i<4000000)
        {
            sum = sum + i;
        }
        
        i = B; // advance to the second, fourth, sixth terms
        
        // determine if we add i to the sum; prevent i from exceeting 4 000 000
        if(i % 2 ==0 && i<4000000)
        {
            sum = sum + i;
        }
        
        //Advance the Fibonnaci sequence
        
        // the next odd indexed term is
        A = A + B;
        
        // the next even indexed term is
        
        B = B + A;
        }while(i<4000000);
    // print the result for all to see
    printf("The answer is %d\n", sum);
    
    return 0;
}
